services:
  htp-suite:
    build: .
    container_name: htp-service-suite
    restart: unless-stopped
    network_mode: "host"
    environment:
      # Die Datenbank wird im /data Ordner abgelegt, der gemountet ist!
      - DATABASE_URL=file:/data/dev.db
    volumes:
      # Dies ist dein heiliger Backup-Ordner! 
      # Alles was in /data im Container landet, wird auf dem Proxmox im Ordner ./htp-data gespeichert.
      - ./htp-data:/data
